### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MitchBradley**
This is an attempt to align the instructions with current build usage.

* Clarified the new behavior of clean, submodules, and mpy_cross and fixed the example build lines with respect to their use
* For embedded Python code examples, used the markdown code inclusion syntax so the code is syntax-highlighted and does not have excess indentation.
* Mentioned the rgb_display driver as an adjunct to the hardcoded drivers.

### CODE REVIEW

**Comment by jd3096-mpy** [comment]
> This is an attempt to align the instructions with current build usage.
> 
> * Clarified the new behavior of clean, submodules, and mpy_cross and fixed the example build lines with respect to their use
> * For embedded Python code examples, used the markdown code inclusion syntax so the code is syntax-highlighted and does not have excess indentation.
> * Mentioned the rgb_display driver as an adjunct to the hardcoded drivers.

Yes, I've always thought that the README of this repository is somewhat inaccurate and not up to date, possibly because the author updates it frequently. At the same time, I also believe there should be an 'examples' folder to store some simple demos. Otherwise, it can be quite challenging for beginners to correctly initialize the hardware.

**Comment by MitchBradley** [comment]
>  I also believe there should be an 'examples' folder to store some simple demos.

Seems like a good idea.  I suspect that if you were to volunteer to be the curator of same, the help would be appreciated.  For starters, there is an example rgb driver at the end of #128

**Comment by kdschlosser** [comment]
the intended lines actually had a purpose.  It was done to make converting from markdown to ReST easier to do when I put together a documentation build system which is going to use Sphinx. Not a deal breaker or anything like that but there was a reason why I had indented the code block like they were.

**Comment by kdschlosser** [comment]
I also created a discussion board so users could add their display startup code for specific boards they are using.

**Pull request merged**
